name: Test action-template

on:
  push:
    paths:
      - "action-template/**"
  pull_request:
    paths:
      - "action-template/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run the template action
        uses: ./action-template
        with:
          example-input: "hello-world"
